create extension if not exists "pg_cron" with schema "pg_catalog";

create sequence "public"."especial-semana_id_seq";


  create table "public"."announcement_bars" (
    "id" uuid not null default gen_random_uuid(),
    "message" text not null,
    "link_url" text,
    "link_label" text,
    "bg_color" text not null default '#1a1a1a'::text,
    "text_color" text not null default '#ffffff'::text,
    "is_active" boolean not null default true,
    "priority" integer not null default 0,
    "starts_at" timestamp with time zone,
    "ends_at" timestamp with time zone,
    "is_closable" boolean not null default true,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."announcement_bars" enable row level security;


  create table "public"."biblioteca" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null,
    "title" character varying not null,
    "html_path" text,
    "pdf_path" text,
    "read_time" integer,
    "updated_at" timestamp with time zone default now(),
    "tema" text not null default 'diversos'::text,
    "index" integer not null default 0
      );


alter table "public"."biblioteca" enable row level security;


  create table "public"."book" (
    "id" bigint generated always as identity not null,
    "title" text not null,
    "subtitle" text,
    "description" text,
    "cover_image_path" text,
    "cover_pdf_path" text,
    "intro_pdf_path" text,
    "badge_text" text,
    "order" integer default 0,
    "is_active" boolean default true,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now(),
    "intro_html_path" text
      );


alter table "public"."book" enable row level security;


  create table "public"."content_digest_queue" (
    "id" uuid not null default gen_random_uuid(),
    "table_name" text not null,
    "record_id" text not null,
    "record_data" jsonb not null,
    "created_at" timestamp with time zone not null default now(),
    "sent_at" timestamp with time zone
      );


alter table "public"."content_digest_queue" enable row level security;


  create table "public"."ebooks" (
    "id" bigint generated always as identity not null,
    "title" text not null,
    "subtitle" text,
    "description" text,
    "cover_image_path" text,
    "cover_pdf_path" text,
    "intro_pdf_path" text,
    "badge_text" text,
    "order" integer default 0,
    "is_active" boolean default true,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now(),
    "intro_html_path" text,
    "read_time" integer
      );


alter table "public"."ebooks" enable row level security;


  create table "public"."editorial" (
    "id" integer not null default 1,
    "content" text not null default ''::text,
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."editorial" enable row level security;


  create table "public"."especial_semana" (
    "id" bigint not null default nextval('public."especial-semana_id_seq"'::regclass),
    "created_at" timestamp with time zone not null default now(),
    "title" text not null,
    "html_path" text,
    "pdf_path" text,
    "read_time" integer not null,
    "updated_at" timestamp with time zone default now(),
    "index" integer not null default 0
      );


alter table "public"."especial_semana" enable row level security;


  create table "public"."estudar" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null,
    "title" character varying not null,
    "html_path" text,
    "pdf_path" text,
    "read_time" integer,
    "updated_at" timestamp with time zone default now(),
    "index" integer not null default 0
      );


alter table "public"."estudar" enable row level security;


  create table "public"."mini_livros" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null,
    "title" character varying not null,
    "html_path" text,
    "pdf_path" text,
    "read_time" integer,
    "updated_at" timestamp with time zone default now(),
    "index" integer not null default 0,
    "ebook_id" bigint,
    "part_order" smallint not null default 1
      );


alter table "public"."mini_livros" enable row level security;


  create table "public"."newsletters" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null,
    "title" character varying not null,
    "html_path" text,
    "pdf_path" text,
    "read_time" integer,
    "updated_at" timestamp with time zone default now(),
    "index" integer not null default 0
      );


alter table "public"."newsletters" enable row level security;


  create table "public"."portal_news" (
    "id" uuid not null default gen_random_uuid(),
    "title" text not null,
    "description" text,
    "icon" text not null,
    "category" text not null,
    "accent_color" text,
    "published_at" timestamp with time zone not null default now(),
    "display_order" integer not null default 0,
    "is_active" boolean not null default true,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now(),
    "link_type" text,
    "link_item_id" integer
      );


alter table "public"."portal_news" enable row level security;


  create table "public"."radar_oportunidades" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null,
    "title" character varying not null,
    "html_path" text,
    "pdf_path" text,
    "read_time" integer,
    "updated_at" timestamp with time zone default now(),
    "index" integer not null default 0
      );


alter table "public"."radar_oportunidades" enable row level security;


  create table "public"."users" (
    "id" uuid not null,
    "email" text not null,
    "nome" text not null,
    "celular" text not null,
    "accept_email_updates" boolean not null default false,
    "accept_whatsapp_updates" boolean not null default false,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."users" enable row level security;

alter sequence "public"."especial-semana_id_seq" owned by "public"."especial_semana"."id";

CREATE UNIQUE INDEX announcement_bars_pkey ON public.announcement_bars USING btree (id);

CREATE UNIQUE INDEX biblioteca_id_key ON public.biblioteca USING btree (id);

CREATE UNIQUE INDEX biblioteca_pkey ON public.biblioteca USING btree (id);

CREATE UNIQUE INDEX biblioteca_title_key ON public.biblioteca USING btree (title);

CREATE UNIQUE INDEX book_pkey ON public.book USING btree (id);

CREATE UNIQUE INDEX content_digest_queue_pkey ON public.content_digest_queue USING btree (id);

CREATE UNIQUE INDEX ebooks_order_unique ON public.ebooks USING btree ("order");

CREATE UNIQUE INDEX ebooks_pkey ON public.ebooks USING btree (id);

CREATE UNIQUE INDEX editorial_pkey ON public.editorial USING btree (id);

CREATE UNIQUE INDEX "especial-semana_pkey" ON public.especial_semana USING btree (id);

CREATE UNIQUE INDEX estudar_id_key ON public.estudar USING btree (id);

CREATE UNIQUE INDEX estudar_pkey ON public.estudar USING btree (id);

CREATE UNIQUE INDEX estudar_title_key ON public.estudar USING btree (title);

CREATE INDEX idx_biblioteca_fts ON public.biblioteca USING gin (to_tsvector('portuguese'::regconfig, (COALESCE(title, ''::character varying))::text));

CREATE INDEX idx_biblioteca_index ON public.biblioteca USING btree (index);

CREATE INDEX idx_biblioteca_tema ON public.biblioteca USING btree (tema);

CREATE INDEX idx_biblioteca_tema_created_at ON public.biblioteca USING btree (tema, created_at DESC);

CREATE INDEX idx_digest_queue_pending ON public.content_digest_queue USING btree (created_at DESC) WHERE (sent_at IS NULL);

CREATE INDEX idx_digest_queue_sent ON public.content_digest_queue USING btree (sent_at DESC) WHERE (sent_at IS NOT NULL);

CREATE INDEX idx_especial_semana_fts ON public.especial_semana USING gin (to_tsvector('portuguese'::regconfig, COALESCE(title, ''::text)));

CREATE INDEX idx_especial_semana_index ON public.especial_semana USING btree (index);

CREATE INDEX idx_estudar_index ON public.estudar USING btree (index);

CREATE INDEX idx_mini_livros_fts ON public.mini_livros USING gin (to_tsvector('portuguese'::regconfig, (COALESCE(title, ''::character varying))::text));

CREATE INDEX idx_mini_livros_index ON public.mini_livros USING btree (index);

CREATE INDEX idx_mini_livros_part_order ON public.mini_livros USING btree (part_order);

CREATE INDEX idx_newsletters_fts ON public.newsletters USING gin (to_tsvector('portuguese'::regconfig, (COALESCE(title, ''::character varying))::text));

CREATE INDEX idx_newsletters_index ON public.newsletters USING btree (index);

CREATE INDEX idx_radar_oportunidades_index ON public.radar_oportunidades USING btree (index);

CREATE UNIQUE INDEX "mini-livros_id_key" ON public.mini_livros USING btree (id);

CREATE UNIQUE INDEX "mini-livros_pkey" ON public.mini_livros USING btree (id);

CREATE UNIQUE INDEX mini_livros_unique_title_per_ebook ON public.mini_livros USING btree (ebook_id, title);

CREATE UNIQUE INDEX newsletters_id_key ON public.newsletters USING btree (id);

CREATE UNIQUE INDEX newsletters_pkey ON public.newsletters USING btree (id);

CREATE UNIQUE INDEX newsletters_title_key ON public.newsletters USING btree (title);

CREATE UNIQUE INDEX portal_news_pkey ON public.portal_news USING btree (id);

CREATE UNIQUE INDEX "radar-oportunidades_id_key" ON public.radar_oportunidades USING btree (id);

CREATE UNIQUE INDEX "radar-oportunidades_pkey" ON public.radar_oportunidades USING btree (id);

CREATE UNIQUE INDEX "radar-oportunidades_title_key" ON public.radar_oportunidades USING btree (title);

CREATE UNIQUE INDEX unique_content_item ON public.content_digest_queue USING btree (table_name, record_id);

CREATE INDEX users_created_at_idx ON public.users USING btree (created_at DESC);

CREATE INDEX users_email_idx ON public.users USING btree (email);

CREATE UNIQUE INDEX users_email_key ON public.users USING btree (email);

CREATE UNIQUE INDEX users_email_unique_idx ON public.users USING btree (lower(email));

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);

alter table "public"."announcement_bars" add constraint "announcement_bars_pkey" PRIMARY KEY using index "announcement_bars_pkey";

alter table "public"."biblioteca" add constraint "biblioteca_pkey" PRIMARY KEY using index "biblioteca_pkey";

alter table "public"."book" add constraint "book_pkey" PRIMARY KEY using index "book_pkey";

alter table "public"."content_digest_queue" add constraint "content_digest_queue_pkey" PRIMARY KEY using index "content_digest_queue_pkey";

alter table "public"."ebooks" add constraint "ebooks_pkey" PRIMARY KEY using index "ebooks_pkey";

alter table "public"."editorial" add constraint "editorial_pkey" PRIMARY KEY using index "editorial_pkey";

alter table "public"."especial_semana" add constraint "especial-semana_pkey" PRIMARY KEY using index "especial-semana_pkey";

alter table "public"."estudar" add constraint "estudar_pkey" PRIMARY KEY using index "estudar_pkey";

alter table "public"."mini_livros" add constraint "mini-livros_pkey" PRIMARY KEY using index "mini-livros_pkey";

alter table "public"."newsletters" add constraint "newsletters_pkey" PRIMARY KEY using index "newsletters_pkey";

alter table "public"."portal_news" add constraint "portal_news_pkey" PRIMARY KEY using index "portal_news_pkey";

alter table "public"."radar_oportunidades" add constraint "radar-oportunidades_pkey" PRIMARY KEY using index "radar-oportunidades_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."biblioteca" add constraint "biblioteca_id_key" UNIQUE using index "biblioteca_id_key";

alter table "public"."biblioteca" add constraint "biblioteca_tema_check" CHECK ((tema = ANY (ARRAY['biblioteca-dos-7'::text, 'saude'::text, 'investimentos-financas'::text, 'viagens-restaurantes'::text, 'tecnologia'::text, 'prompts'::text, 'diversos'::text]))) not valid;

alter table "public"."biblioteca" validate constraint "biblioteca_tema_check";

alter table "public"."biblioteca" add constraint "biblioteca_title_key" UNIQUE using index "biblioteca_title_key";

alter table "public"."content_digest_queue" add constraint "unique_content_item" UNIQUE using index "unique_content_item";

alter table "public"."ebooks" add constraint "ebooks_order_unique" UNIQUE using index "ebooks_order_unique";

alter table "public"."editorial" add constraint "editorial_single_row" CHECK ((id = 1)) not valid;

alter table "public"."editorial" validate constraint "editorial_single_row";

alter table "public"."especial_semana" add constraint "especial-semana_read_time_check" CHECK ((read_time > 0)) not valid;

alter table "public"."especial_semana" validate constraint "especial-semana_read_time_check";

alter table "public"."estudar" add constraint "estudar_id_key" UNIQUE using index "estudar_id_key";

alter table "public"."estudar" add constraint "estudar_title_key" UNIQUE using index "estudar_title_key";

alter table "public"."mini_livros" add constraint "mini-livros_id_key" UNIQUE using index "mini-livros_id_key";

alter table "public"."mini_livros" add constraint "mini_livros_ebook_id_fkey" FOREIGN KEY (ebook_id) REFERENCES public.ebooks(id) ON DELETE SET NULL not valid;

alter table "public"."mini_livros" validate constraint "mini_livros_ebook_id_fkey";

alter table "public"."mini_livros" add constraint "mini_livros_part_order_check" CHECK (((part_order >= 1) AND (part_order <= 3))) not valid;

alter table "public"."mini_livros" validate constraint "mini_livros_part_order_check";

alter table "public"."mini_livros" add constraint "mini_livros_unique_title_per_ebook" UNIQUE using index "mini_livros_unique_title_per_ebook";

alter table "public"."newsletters" add constraint "newsletters_id_key" UNIQUE using index "newsletters_id_key";

alter table "public"."newsletters" add constraint "newsletters_title_key" UNIQUE using index "newsletters_title_key";

alter table "public"."portal_news" add constraint "portal_news_category_check" CHECK ((category = ANY (ARRAY['launch'::text, 'newsletter'::text, 'content'::text, 'tool'::text]))) not valid;

alter table "public"."portal_news" validate constraint "portal_news_category_check";

alter table "public"."portal_news" add constraint "portal_news_link_type_check" CHECK (((link_type IS NULL) OR (link_type = ANY (ARRAY['newsletter'::text, 'mini-livro'::text, 'biblioteca'::text, 'especial-semana'::text, 'radar-oportunidades'::text, 'estudar'::text])))) not valid;

alter table "public"."portal_news" validate constraint "portal_news_link_type_check";

alter table "public"."radar_oportunidades" add constraint "radar-oportunidades_id_key" UNIQUE using index "radar-oportunidades_id_key";

alter table "public"."radar_oportunidades" add constraint "radar-oportunidades_title_key" UNIQUE using index "radar-oportunidades_title_key";

alter table "public"."users" add constraint "users_celular_check" CHECK ((length(regexp_replace(celular, '[^0-9]'::text, ''::text, 'g'::text)) >= 10)) not valid;

alter table "public"."users" validate constraint "users_celular_check";

alter table "public"."users" add constraint "users_consent_check" CHECK (((accept_email_updates = true) OR (accept_whatsapp_updates = true))) not valid;

alter table "public"."users" validate constraint "users_consent_check";

alter table "public"."users" add constraint "users_email_check" CHECK ((email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text)) not valid;

alter table "public"."users" validate constraint "users_email_check";

alter table "public"."users" add constraint "users_email_key" UNIQUE using index "users_email_key";

alter table "public"."users" add constraint "users_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."users" validate constraint "users_id_fkey";

alter table "public"."users" add constraint "users_nome_check" CHECK ((length(TRIM(BOTH FROM nome)) > 0)) not valid;

alter table "public"."users" validate constraint "users_nome_check";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.count_admins()
 RETURNS integer
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'auth'
AS $function$
BEGIN
    -- VALIDAÇÃO OBRIGATÓRIA: apenas admins podem chamar
    -- Se não-admin tentar via DevTools ou API direta: EXCEPTION
    IF NOT public.is_admin() THEN
        RAISE EXCEPTION 'Acesso negado: apenas administradores podem acessar esta função';
    END IF;

    -- Retornar contagem apenas se passou validação acima
    RETURN (
        SELECT COUNT(*)::INTEGER
        FROM auth.users
        WHERE raw_app_meta_data->>'role' = 'admin'
    );
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_user_profile(user_id uuid)
 RETURNS TABLE(id uuid, email text, nome text, celular text, accept_email_updates boolean, accept_whatsapp_updates boolean, created_at timestamp with time zone, updated_at timestamp with time zone)
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
    RETURN QUERY
    SELECT 
        u.id,
        u.email,
        u.nome,
        u.celular,
        u.accept_email_updates,
        u.accept_whatsapp_updates,
        u.created_at,
        u.updated_at
    FROM public.users u
    WHERE u.id = user_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
    INSERT INTO public.users (
        id,
        email,
        nome,
        celular,
        accept_email_updates,
        accept_whatsapp_updates
    ) VALUES (
        NEW.id,
        NEW.email,
        COALESCE(NEW.raw_user_meta_data->>'nome', 'Usuário'),
        COALESCE(NEW.raw_user_meta_data->>'celular', ''),
        COALESCE((NEW.raw_user_meta_data->>'accept_email_updates')::boolean, false),
        COALESCE((NEW.raw_user_meta_data->>'accept_whatsapp_updates')::boolean, false)
    );
    RETURN NEW;
EXCEPTION
    WHEN others THEN
        RAISE WARNING 'Erro ao criar perfil: %', SQLERRM;
        RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.is_admin()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
    SELECT COALESCE(
        (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin',
        false
    );
$function$
;

create materialized view "public"."mv_admin_dashboard_stats" as  SELECT ( SELECT count(*) AS count
           FROM public.newsletters) AS total_newsletters,
    ( SELECT count(*) AS count
           FROM public.mini_livros) AS total_mini_livros,
    ( SELECT count(*) AS count
           FROM public.biblioteca) AS total_biblioteca,
    ( SELECT count(*) AS count
           FROM public.especial_semana) AS total_especial_semana,
    ( SELECT count(*) AS count
           FROM public.ebooks) AS total_ebooks,
    ( SELECT count(*) AS count
           FROM public.radar_oportunidades) AS total_radar_oportunidades,
    ( SELECT count(*) AS count
           FROM public.estudar) AS total_estudar,
    ((((((( SELECT count(*) AS count
           FROM public.newsletters) + ( SELECT count(*) AS count
           FROM public.mini_livros)) + ( SELECT count(*) AS count
           FROM public.biblioteca)) + ( SELECT count(*) AS count
           FROM public.especial_semana)) + ( SELECT count(*) AS count
           FROM public.ebooks)) + ( SELECT count(*) AS count
           FROM public.radar_oportunidades)) + ( SELECT count(*) AS count
           FROM public.estudar)) AS total_content,
    ( SELECT count(*) AS count
           FROM public.users) AS total_users,
    ( SELECT count(*) AS count
           FROM public.users
          WHERE (users.created_at >= (now() - '30 days'::interval))) AS new_users_last_30_days,
    ( SELECT count(*) AS count
           FROM auth.users
          WHERE ((users.raw_app_meta_data ->> 'role'::text) = 'admin'::text)) AS total_admins;


create materialized view "public"."mv_home_latest_dates" as  SELECT 'newsletter'::text AS section_name,
    max(newsletters.created_at) AS latest_created_at
   FROM public.newsletters
  WHERE (newsletters.created_at IS NOT NULL)
UNION ALL
 SELECT 'especial_semana'::text AS section_name,
    max(especial_semana.created_at) AS latest_created_at
   FROM public.especial_semana
  WHERE (especial_semana.created_at IS NOT NULL)
UNION ALL
 SELECT 'radar_oportunidades'::text AS section_name,
    max(radar_oportunidades.created_at) AS latest_created_at
   FROM public.radar_oportunidades
  WHERE (radar_oportunidades.created_at IS NOT NULL)
UNION ALL
 SELECT 'mini_livros'::text AS section_name,
    max(mini_livros.created_at) AS latest_created_at
   FROM public.mini_livros
  WHERE (mini_livros.created_at IS NOT NULL)
UNION ALL
 SELECT 'biblioteca'::text AS section_name,
    max(biblioteca.created_at) AS latest_created_at
   FROM public.biblioteca
  WHERE (biblioteca.created_at IS NOT NULL)
UNION ALL
 SELECT 'estudar'::text AS section_name,
    max(estudar.created_at) AS latest_created_at
   FROM public.estudar
  WHERE (estudar.created_at IS NOT NULL);


CREATE OR REPLACE FUNCTION public.queue_content_for_digest()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  -- Insere registro na fila de digest
  -- Se já existir (tabela + id), ignora (ON CONFLICT DO NOTHING)
  INSERT INTO public.content_digest_queue (table_name, record_id, record_data)
  VALUES (
    TG_TABLE_NAME,
    NEW.id::text,
    jsonb_build_object(
      'id', NEW.id,
      'title', NEW.title,
      'read_time', NEW.read_time,
      'created_at', NEW.created_at
    )
  )
  ON CONFLICT (table_name, record_id) DO NOTHING;
  
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.refresh_mv_admin_dashboard_stats()
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  -- Database-level admin check
  IF (auth.jwt() -> 'app_metadata' ->> 'role')::text != 'admin' THEN
    RAISE EXCEPTION 'Unauthorized: Admin access required';
  END IF;

  -- Refresh with CONCURRENTLY
  -- Requires unique index: idx_mv_dashboard_stats_singleton
  REFRESH MATERIALIZED VIEW CONCURRENTLY mv_admin_dashboard_stats;
  
  -- Log success
  RAISE NOTICE 'Successfully refreshed mv_admin_dashboard_stats';
END;
$function$
;

CREATE OR REPLACE FUNCTION public.refresh_mv_home_latest_dates()
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  -- Database-level admin check (not TypeScript - this is real security)
  -- TypeScript checks are UX only (anon key is public, can be bypassed)
  IF (auth.jwt() -> 'app_metadata' ->> 'role')::text != 'admin' THEN
    RAISE EXCEPTION 'Unauthorized: Admin access required';
  END IF;

  -- Refresh with CONCURRENTLY (non-blocking for readers)
  -- Requires unique index: idx_mv_home_dates_section
  REFRESH MATERIALIZED VIEW CONCURRENTLY mv_home_latest_dates;
  
  -- Log success (visible in Supabase Dashboard logs)
  RAISE NOTICE 'Successfully refreshed mv_home_latest_dates';
END;
$function$
;

CREATE OR REPLACE FUNCTION public.rls_auto_enable()
 RETURNS event_trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$
;

create or replace view "public"."vw_searchable_content" as  SELECT 'newsletter'::text AS content_type,
    newsletters.id,
    newsletters.title,
    newsletters.created_at,
    newsletters.html_path,
    newsletters.pdf_path,
    newsletters.read_time,
    to_tsvector('portuguese'::regconfig, (COALESCE(newsletters.title, ''::character varying))::text) AS title_ts
   FROM public.newsletters
UNION ALL
 SELECT 'mini_livro'::text AS content_type,
    mini_livros.id,
    mini_livros.title,
    mini_livros.created_at,
    mini_livros.html_path,
    mini_livros.pdf_path,
    mini_livros.read_time,
    to_tsvector('portuguese'::regconfig, (COALESCE(mini_livros.title, ''::character varying))::text) AS title_ts
   FROM public.mini_livros
UNION ALL
 SELECT 'biblioteca'::text AS content_type,
    biblioteca.id,
    biblioteca.title,
    biblioteca.created_at,
    biblioteca.html_path,
    biblioteca.pdf_path,
    biblioteca.read_time,
    to_tsvector('portuguese'::regconfig, (COALESCE(biblioteca.title, ''::character varying))::text) AS title_ts
   FROM public.biblioteca
UNION ALL
 SELECT 'especial_semana'::text AS content_type,
    especial_semana.id,
    especial_semana.title,
    especial_semana.created_at,
    especial_semana.html_path,
    especial_semana.pdf_path,
    especial_semana.read_time,
    to_tsvector('portuguese'::regconfig, COALESCE(especial_semana.title, ''::text)) AS title_ts
   FROM public.especial_semana;


CREATE UNIQUE INDEX idx_mv_dashboard_stats_singleton ON public.mv_admin_dashboard_stats USING btree ((true));

CREATE UNIQUE INDEX idx_mv_home_dates_section ON public.mv_home_latest_dates USING btree (section_name);

grant delete on table "public"."announcement_bars" to "anon";

grant insert on table "public"."announcement_bars" to "anon";

grant references on table "public"."announcement_bars" to "anon";

grant select on table "public"."announcement_bars" to "anon";

grant trigger on table "public"."announcement_bars" to "anon";

grant truncate on table "public"."announcement_bars" to "anon";

grant update on table "public"."announcement_bars" to "anon";

grant delete on table "public"."announcement_bars" to "authenticated";

grant insert on table "public"."announcement_bars" to "authenticated";

grant references on table "public"."announcement_bars" to "authenticated";

grant select on table "public"."announcement_bars" to "authenticated";

grant trigger on table "public"."announcement_bars" to "authenticated";

grant truncate on table "public"."announcement_bars" to "authenticated";

grant update on table "public"."announcement_bars" to "authenticated";

grant delete on table "public"."announcement_bars" to "service_role";

grant insert on table "public"."announcement_bars" to "service_role";

grant references on table "public"."announcement_bars" to "service_role";

grant select on table "public"."announcement_bars" to "service_role";

grant trigger on table "public"."announcement_bars" to "service_role";

grant truncate on table "public"."announcement_bars" to "service_role";

grant update on table "public"."announcement_bars" to "service_role";

grant delete on table "public"."biblioteca" to "anon";

grant insert on table "public"."biblioteca" to "anon";

grant references on table "public"."biblioteca" to "anon";

grant select on table "public"."biblioteca" to "anon";

grant trigger on table "public"."biblioteca" to "anon";

grant truncate on table "public"."biblioteca" to "anon";

grant update on table "public"."biblioteca" to "anon";

grant delete on table "public"."biblioteca" to "authenticated";

grant insert on table "public"."biblioteca" to "authenticated";

grant references on table "public"."biblioteca" to "authenticated";

grant select on table "public"."biblioteca" to "authenticated";

grant trigger on table "public"."biblioteca" to "authenticated";

grant truncate on table "public"."biblioteca" to "authenticated";

grant update on table "public"."biblioteca" to "authenticated";

grant delete on table "public"."biblioteca" to "service_role";

grant insert on table "public"."biblioteca" to "service_role";

grant references on table "public"."biblioteca" to "service_role";

grant select on table "public"."biblioteca" to "service_role";

grant trigger on table "public"."biblioteca" to "service_role";

grant truncate on table "public"."biblioteca" to "service_role";

grant update on table "public"."biblioteca" to "service_role";

grant delete on table "public"."book" to "anon";

grant insert on table "public"."book" to "anon";

grant references on table "public"."book" to "anon";

grant select on table "public"."book" to "anon";

grant trigger on table "public"."book" to "anon";

grant truncate on table "public"."book" to "anon";

grant update on table "public"."book" to "anon";

grant delete on table "public"."book" to "authenticated";

grant insert on table "public"."book" to "authenticated";

grant references on table "public"."book" to "authenticated";

grant select on table "public"."book" to "authenticated";

grant trigger on table "public"."book" to "authenticated";

grant truncate on table "public"."book" to "authenticated";

grant update on table "public"."book" to "authenticated";

grant delete on table "public"."book" to "service_role";

grant insert on table "public"."book" to "service_role";

grant references on table "public"."book" to "service_role";

grant select on table "public"."book" to "service_role";

grant trigger on table "public"."book" to "service_role";

grant truncate on table "public"."book" to "service_role";

grant update on table "public"."book" to "service_role";

grant delete on table "public"."content_digest_queue" to "anon";

grant insert on table "public"."content_digest_queue" to "anon";

grant references on table "public"."content_digest_queue" to "anon";

grant select on table "public"."content_digest_queue" to "anon";

grant trigger on table "public"."content_digest_queue" to "anon";

grant truncate on table "public"."content_digest_queue" to "anon";

grant update on table "public"."content_digest_queue" to "anon";

grant delete on table "public"."content_digest_queue" to "authenticated";

grant insert on table "public"."content_digest_queue" to "authenticated";

grant references on table "public"."content_digest_queue" to "authenticated";

grant select on table "public"."content_digest_queue" to "authenticated";

grant trigger on table "public"."content_digest_queue" to "authenticated";

grant truncate on table "public"."content_digest_queue" to "authenticated";

grant update on table "public"."content_digest_queue" to "authenticated";

grant delete on table "public"."content_digest_queue" to "service_role";

grant insert on table "public"."content_digest_queue" to "service_role";

grant references on table "public"."content_digest_queue" to "service_role";

grant select on table "public"."content_digest_queue" to "service_role";

grant trigger on table "public"."content_digest_queue" to "service_role";

grant truncate on table "public"."content_digest_queue" to "service_role";

grant update on table "public"."content_digest_queue" to "service_role";

grant delete on table "public"."ebooks" to "anon";

grant insert on table "public"."ebooks" to "anon";

grant references on table "public"."ebooks" to "anon";

grant select on table "public"."ebooks" to "anon";

grant trigger on table "public"."ebooks" to "anon";

grant truncate on table "public"."ebooks" to "anon";

grant update on table "public"."ebooks" to "anon";

grant delete on table "public"."ebooks" to "authenticated";

grant insert on table "public"."ebooks" to "authenticated";

grant references on table "public"."ebooks" to "authenticated";

grant select on table "public"."ebooks" to "authenticated";

grant trigger on table "public"."ebooks" to "authenticated";

grant truncate on table "public"."ebooks" to "authenticated";

grant update on table "public"."ebooks" to "authenticated";

grant delete on table "public"."ebooks" to "service_role";

grant insert on table "public"."ebooks" to "service_role";

grant references on table "public"."ebooks" to "service_role";

grant select on table "public"."ebooks" to "service_role";

grant trigger on table "public"."ebooks" to "service_role";

grant truncate on table "public"."ebooks" to "service_role";

grant update on table "public"."ebooks" to "service_role";

grant delete on table "public"."editorial" to "anon";

grant insert on table "public"."editorial" to "anon";

grant references on table "public"."editorial" to "anon";

grant select on table "public"."editorial" to "anon";

grant trigger on table "public"."editorial" to "anon";

grant truncate on table "public"."editorial" to "anon";

grant update on table "public"."editorial" to "anon";

grant delete on table "public"."editorial" to "authenticated";

grant insert on table "public"."editorial" to "authenticated";

grant references on table "public"."editorial" to "authenticated";

grant select on table "public"."editorial" to "authenticated";

grant trigger on table "public"."editorial" to "authenticated";

grant truncate on table "public"."editorial" to "authenticated";

grant update on table "public"."editorial" to "authenticated";

grant delete on table "public"."editorial" to "service_role";

grant insert on table "public"."editorial" to "service_role";

grant references on table "public"."editorial" to "service_role";

grant select on table "public"."editorial" to "service_role";

grant trigger on table "public"."editorial" to "service_role";

grant truncate on table "public"."editorial" to "service_role";

grant update on table "public"."editorial" to "service_role";

grant delete on table "public"."especial_semana" to "anon";

grant insert on table "public"."especial_semana" to "anon";

grant references on table "public"."especial_semana" to "anon";

grant select on table "public"."especial_semana" to "anon";

grant trigger on table "public"."especial_semana" to "anon";

grant truncate on table "public"."especial_semana" to "anon";

grant update on table "public"."especial_semana" to "anon";

grant delete on table "public"."especial_semana" to "authenticated";

grant insert on table "public"."especial_semana" to "authenticated";

grant references on table "public"."especial_semana" to "authenticated";

grant select on table "public"."especial_semana" to "authenticated";

grant trigger on table "public"."especial_semana" to "authenticated";

grant truncate on table "public"."especial_semana" to "authenticated";

grant update on table "public"."especial_semana" to "authenticated";

grant delete on table "public"."especial_semana" to "service_role";

grant insert on table "public"."especial_semana" to "service_role";

grant references on table "public"."especial_semana" to "service_role";

grant select on table "public"."especial_semana" to "service_role";

grant trigger on table "public"."especial_semana" to "service_role";

grant truncate on table "public"."especial_semana" to "service_role";

grant update on table "public"."especial_semana" to "service_role";

grant delete on table "public"."estudar" to "anon";

grant insert on table "public"."estudar" to "anon";

grant references on table "public"."estudar" to "anon";

grant select on table "public"."estudar" to "anon";

grant trigger on table "public"."estudar" to "anon";

grant truncate on table "public"."estudar" to "anon";

grant update on table "public"."estudar" to "anon";

grant delete on table "public"."estudar" to "authenticated";

grant insert on table "public"."estudar" to "authenticated";

grant references on table "public"."estudar" to "authenticated";

grant select on table "public"."estudar" to "authenticated";

grant trigger on table "public"."estudar" to "authenticated";

grant truncate on table "public"."estudar" to "authenticated";

grant update on table "public"."estudar" to "authenticated";

grant delete on table "public"."estudar" to "service_role";

grant insert on table "public"."estudar" to "service_role";

grant references on table "public"."estudar" to "service_role";

grant select on table "public"."estudar" to "service_role";

grant trigger on table "public"."estudar" to "service_role";

grant truncate on table "public"."estudar" to "service_role";

grant update on table "public"."estudar" to "service_role";

grant delete on table "public"."mini_livros" to "anon";

grant insert on table "public"."mini_livros" to "anon";

grant references on table "public"."mini_livros" to "anon";

grant select on table "public"."mini_livros" to "anon";

grant trigger on table "public"."mini_livros" to "anon";

grant truncate on table "public"."mini_livros" to "anon";

grant update on table "public"."mini_livros" to "anon";

grant delete on table "public"."mini_livros" to "authenticated";

grant insert on table "public"."mini_livros" to "authenticated";

grant references on table "public"."mini_livros" to "authenticated";

grant select on table "public"."mini_livros" to "authenticated";

grant trigger on table "public"."mini_livros" to "authenticated";

grant truncate on table "public"."mini_livros" to "authenticated";

grant update on table "public"."mini_livros" to "authenticated";

grant delete on table "public"."mini_livros" to "service_role";

grant insert on table "public"."mini_livros" to "service_role";

grant references on table "public"."mini_livros" to "service_role";

grant select on table "public"."mini_livros" to "service_role";

grant trigger on table "public"."mini_livros" to "service_role";

grant truncate on table "public"."mini_livros" to "service_role";

grant update on table "public"."mini_livros" to "service_role";

grant delete on table "public"."newsletters" to "anon";

grant insert on table "public"."newsletters" to "anon";

grant references on table "public"."newsletters" to "anon";

grant select on table "public"."newsletters" to "anon";

grant trigger on table "public"."newsletters" to "anon";

grant truncate on table "public"."newsletters" to "anon";

grant update on table "public"."newsletters" to "anon";

grant delete on table "public"."newsletters" to "authenticated";

grant insert on table "public"."newsletters" to "authenticated";

grant references on table "public"."newsletters" to "authenticated";

grant select on table "public"."newsletters" to "authenticated";

grant trigger on table "public"."newsletters" to "authenticated";

grant truncate on table "public"."newsletters" to "authenticated";

grant update on table "public"."newsletters" to "authenticated";

grant delete on table "public"."newsletters" to "service_role";

grant insert on table "public"."newsletters" to "service_role";

grant references on table "public"."newsletters" to "service_role";

grant select on table "public"."newsletters" to "service_role";

grant trigger on table "public"."newsletters" to "service_role";

grant truncate on table "public"."newsletters" to "service_role";

grant update on table "public"."newsletters" to "service_role";

grant delete on table "public"."portal_news" to "anon";

grant insert on table "public"."portal_news" to "anon";

grant references on table "public"."portal_news" to "anon";

grant select on table "public"."portal_news" to "anon";

grant trigger on table "public"."portal_news" to "anon";

grant truncate on table "public"."portal_news" to "anon";

grant update on table "public"."portal_news" to "anon";

grant delete on table "public"."portal_news" to "authenticated";

grant insert on table "public"."portal_news" to "authenticated";

grant references on table "public"."portal_news" to "authenticated";

grant select on table "public"."portal_news" to "authenticated";

grant trigger on table "public"."portal_news" to "authenticated";

grant truncate on table "public"."portal_news" to "authenticated";

grant update on table "public"."portal_news" to "authenticated";

grant delete on table "public"."portal_news" to "service_role";

grant insert on table "public"."portal_news" to "service_role";

grant references on table "public"."portal_news" to "service_role";

grant select on table "public"."portal_news" to "service_role";

grant trigger on table "public"."portal_news" to "service_role";

grant truncate on table "public"."portal_news" to "service_role";

grant update on table "public"."portal_news" to "service_role";

grant delete on table "public"."radar_oportunidades" to "anon";

grant insert on table "public"."radar_oportunidades" to "anon";

grant references on table "public"."radar_oportunidades" to "anon";

grant select on table "public"."radar_oportunidades" to "anon";

grant trigger on table "public"."radar_oportunidades" to "anon";

grant truncate on table "public"."radar_oportunidades" to "anon";

grant update on table "public"."radar_oportunidades" to "anon";

grant delete on table "public"."radar_oportunidades" to "authenticated";

grant insert on table "public"."radar_oportunidades" to "authenticated";

grant references on table "public"."radar_oportunidades" to "authenticated";

grant select on table "public"."radar_oportunidades" to "authenticated";

grant trigger on table "public"."radar_oportunidades" to "authenticated";

grant truncate on table "public"."radar_oportunidades" to "authenticated";

grant update on table "public"."radar_oportunidades" to "authenticated";

grant delete on table "public"."radar_oportunidades" to "service_role";

grant insert on table "public"."radar_oportunidades" to "service_role";

grant references on table "public"."radar_oportunidades" to "service_role";

grant select on table "public"."radar_oportunidades" to "service_role";

grant trigger on table "public"."radar_oportunidades" to "service_role";

grant truncate on table "public"."radar_oportunidades" to "service_role";

grant update on table "public"."radar_oportunidades" to "service_role";

grant delete on table "public"."users" to "anon";

grant insert on table "public"."users" to "anon";

grant references on table "public"."users" to "anon";

grant select on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant truncate on table "public"."users" to "anon";

grant update on table "public"."users" to "anon";

grant delete on table "public"."users" to "authenticated";

grant insert on table "public"."users" to "authenticated";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant truncate on table "public"."users" to "authenticated";

grant update on table "public"."users" to "authenticated";

grant delete on table "public"."users" to "service_role";

grant insert on table "public"."users" to "service_role";

grant references on table "public"."users" to "service_role";

grant select on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant truncate on table "public"."users" to "service_role";

grant update on table "public"."users" to "service_role";


  create policy "Escrita restrita a autenticados"
  on "public"."announcement_bars"
  as permissive
  for all
  to public
using ((auth.role() = 'authenticated'::text));



  create policy "Leitura pública"
  on "public"."announcement_bars"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."biblioteca"
  as permissive
  for select
  to public
using (true);



  create policy "biblioteca_delete_admin"
  on "public"."biblioteca"
  as permissive
  for delete
  to public
using (public.is_admin());



  create policy "biblioteca_insert_admin"
  on "public"."biblioteca"
  as permissive
  for insert
  to public
with check (public.is_admin());



  create policy "biblioteca_select_public"
  on "public"."biblioteca"
  as permissive
  for select
  to public
using (true);



  create policy "biblioteca_update_admin"
  on "public"."biblioteca"
  as permissive
  for update
  to public
using (public.is_admin())
with check (public.is_admin());



  create policy "book_public_read"
  on "public"."book"
  as permissive
  for select
  to public
using (true);



  create policy "ebooks_delete_admin"
  on "public"."ebooks"
  as permissive
  for delete
  to public
using (public.is_admin());



  create policy "ebooks_insert_admin"
  on "public"."ebooks"
  as permissive
  for insert
  to public
with check (public.is_admin());



  create policy "ebooks_select_public"
  on "public"."ebooks"
  as permissive
  for select
  to public
using (true);



  create policy "ebooks_update_admin"
  on "public"."ebooks"
  as permissive
  for update
  to public
using (public.is_admin());



  create policy "editorial_admin_write"
  on "public"."editorial"
  as permissive
  for all
  to authenticated
using (true);



  create policy "editorial_public_read"
  on "public"."editorial"
  as permissive
  for select
  to public
using (true);



  create policy "especial_semana_delete_admin"
  on "public"."especial_semana"
  as permissive
  for delete
  to public
using (public.is_admin());



  create policy "especial_semana_insert_admin"
  on "public"."especial_semana"
  as permissive
  for insert
  to public
with check (public.is_admin());



  create policy "especial_semana_select_public"
  on "public"."especial_semana"
  as permissive
  for select
  to public
using (true);



  create policy "especial_semana_update_admin"
  on "public"."especial_semana"
  as permissive
  for update
  to public
using (public.is_admin())
with check (public.is_admin());



  create policy "estudar_delete_admin"
  on "public"."estudar"
  as permissive
  for delete
  to public
using (public.is_admin());



  create policy "estudar_insert_admin"
  on "public"."estudar"
  as permissive
  for insert
  to public
with check (public.is_admin());



  create policy "estudar_select_public"
  on "public"."estudar"
  as permissive
  for select
  to public
using (true);



  create policy "estudar_update_admin"
  on "public"."estudar"
  as permissive
  for update
  to public
using (public.is_admin());



  create policy "Enable read access for all users"
  on "public"."mini_livros"
  as permissive
  for select
  to public
using (true);



  create policy "mini-livros_delete_admin"
  on "public"."mini_livros"
  as permissive
  for delete
  to public
using (public.is_admin());



  create policy "mini-livros_insert_admin"
  on "public"."mini_livros"
  as permissive
  for insert
  to public
with check (public.is_admin());



  create policy "mini-livros_select_public"
  on "public"."mini_livros"
  as permissive
  for select
  to public
using (true);



  create policy "mini-livros_update_admin"
  on "public"."mini_livros"
  as permissive
  for update
  to public
using (public.is_admin());



  create policy "mini_livros_delete_admin"
  on "public"."mini_livros"
  as permissive
  for delete
  to public
using (public.is_admin());



  create policy "mini_livros_insert_admin"
  on "public"."mini_livros"
  as permissive
  for insert
  to public
with check (public.is_admin());



  create policy "mini_livros_select_public"
  on "public"."mini_livros"
  as permissive
  for select
  to public
using (true);



  create policy "mini_livros_update_admin"
  on "public"."mini_livros"
  as permissive
  for update
  to public
using (public.is_admin())
with check (public.is_admin());



  create policy "Enable read access for all users"
  on "public"."newsletters"
  as permissive
  for select
  to public
using (true);



  create policy "newsletters_delete_admin"
  on "public"."newsletters"
  as permissive
  for delete
  to public
using (public.is_admin());



  create policy "newsletters_insert_admin"
  on "public"."newsletters"
  as permissive
  for insert
  to public
with check (public.is_admin());



  create policy "newsletters_insert_public"
  on "public"."newsletters"
  as permissive
  for insert
  to public
with check (true);



  create policy "newsletters_select_public"
  on "public"."newsletters"
  as permissive
  for select
  to public
using (true);



  create policy "newsletters_update_admin"
  on "public"."newsletters"
  as permissive
  for update
  to public
using (public.is_admin())
with check (public.is_admin());



  create policy "portal_news_delete_admin"
  on "public"."portal_news"
  as permissive
  for delete
  to public
using (public.is_admin());



  create policy "portal_news_insert_admin"
  on "public"."portal_news"
  as permissive
  for insert
  to public
with check (public.is_admin());



  create policy "portal_news_select_public"
  on "public"."portal_news"
  as permissive
  for select
  to public
using (true);



  create policy "portal_news_update_admin"
  on "public"."portal_news"
  as permissive
  for update
  to public
using (public.is_admin())
with check (public.is_admin());



  create policy "radar_oportunidades_delete_admin"
  on "public"."radar_oportunidades"
  as permissive
  for delete
  to public
using (public.is_admin());



  create policy "radar_oportunidades_insert_admin"
  on "public"."radar_oportunidades"
  as permissive
  for insert
  to public
with check (public.is_admin());



  create policy "radar_oportunidades_select_public"
  on "public"."radar_oportunidades"
  as permissive
  for select
  to public
using (true);



  create policy "radar_oportunidades_update_admin"
  on "public"."radar_oportunidades"
  as permissive
  for update
  to public
using (public.is_admin());



  create policy "Users can delete own data"
  on "public"."users"
  as permissive
  for delete
  to public
using ((auth.uid() = id));



  create policy "Users can insert own profile"
  on "public"."users"
  as permissive
  for insert
  to public
with check ((auth.uid() = id));



  create policy "Users can read own data"
  on "public"."users"
  as permissive
  for select
  to public
using ((auth.uid() = id));



  create policy "Users can update own data"
  on "public"."users"
  as permissive
  for update
  to public
using ((auth.uid() = id))
with check ((auth.uid() = id));



  create policy "admin_select_all_users"
  on "public"."users"
  as permissive
  for select
  to public
using (public.is_admin());


CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.announcement_bars FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

CREATE TRIGGER trg_queue_digest_biblioteca AFTER INSERT ON public.biblioteca FOR EACH ROW EXECUTE FUNCTION public.queue_content_for_digest();

CREATE TRIGGER trg_queue_digest_ebooks AFTER INSERT ON public.ebooks FOR EACH ROW EXECUTE FUNCTION public.queue_content_for_digest();

CREATE TRIGGER trg_queue_digest_especial_semana AFTER INSERT ON public.especial_semana FOR EACH ROW EXECUTE FUNCTION public.queue_content_for_digest();

CREATE TRIGGER trg_queue_digest_estudar AFTER INSERT ON public.estudar FOR EACH ROW EXECUTE FUNCTION public.queue_content_for_digest();

CREATE TRIGGER trg_queue_digest_mini_livros AFTER INSERT ON public.mini_livros FOR EACH ROW EXECUTE FUNCTION public.queue_content_for_digest();

CREATE TRIGGER trg_newsletters_updated_at BEFORE UPDATE ON public.newsletters FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_queue_digest_newsletters AFTER INSERT ON public.newsletters FOR EACH ROW EXECUTE FUNCTION public.queue_content_for_digest();

CREATE TRIGGER trg_portal_news_updated_at BEFORE UPDATE ON public.portal_news FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_queue_digest_radar_oportunidades AFTER INSERT ON public.radar_oportunidades FOR EACH ROW EXECUTE FUNCTION public.queue_content_for_digest();

CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


  create policy "materiais_delete_admin"
  on "storage"."objects"
  as permissive
  for delete
  to public
using (((bucket_id = 'materiais'::text) AND public.is_admin()));



  create policy "materiais_insert_admin"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check (((bucket_id = 'materiais'::text) AND public.is_admin()));



  create policy "materiais_select_public"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'materiais'::text));



  create policy "materiais_update_admin"
  on "storage"."objects"
  as permissive
  for update
  to public
using (((bucket_id = 'materiais'::text) AND public.is_admin()));



  create policy "storage_delete_admin"
  on "storage"."objects"
  as permissive
  for delete
  to public
using (public.is_admin());



  create policy "storage_delete_biblioteca"
  on "storage"."objects"
  as permissive
  for delete
  to public
using (((bucket_id = 'Biblioteca'::text) AND public.is_admin()));



  create policy "storage_delete_minilivros"
  on "storage"."objects"
  as permissive
  for delete
  to public
using (((bucket_id = 'MiniLivros'::text) AND public.is_admin()));



  create policy "storage_insert_admin"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check (public.is_admin());



  create policy "storage_insert_biblioteca"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check (((bucket_id = 'Biblioteca'::text) AND public.is_admin()));



  create policy "storage_select_biblioteca"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'Biblioteca'::text));



  create policy "storage_select_minilivros"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'MiniLivros'::text));



  create policy "storage_select_public"
  on "storage"."objects"
  as permissive
  for select
  to public
using (true);



  create policy "storage_update_admin"
  on "storage"."objects"
  as permissive
  for update
  to public
using (public.is_admin());



  create policy "storage_update_biblioteca"
  on "storage"."objects"
  as permissive
  for update
  to public
using (((bucket_id = 'Biblioteca'::text) AND public.is_admin()))
with check (((bucket_id = 'Biblioteca'::text) AND public.is_admin()));



  create policy "storage_update_minilivros"
  on "storage"."objects"
  as permissive
  for update
  to public
using (((bucket_id = 'MiniLivros'::text) AND public.is_admin()))
with check (((bucket_id = 'MiniLivros'::text) AND public.is_admin()));



