name: Deploy to Vercel
on:
    push:
        branches:
            - main
            - develop
    pull_request:
        types:
            - closed
        branches:
            - main
            - develop
jobs:
    deploy:
        if: |
            (github.event_name == 'push' && contains(fromJSON('["RaphaelSilva09", "MerigoDavi"]'), github.actor)) ||
            (github.event_name == 'pull_request' && github.event.pull_request.merged == true && contains(fromJSON('["RaphaelSilva09", "MerigoDavi"]'), github.event.pull_request.merged_by.login))
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Install Vercel CLI
              run: npm install --global vercel@latest
            - name: Trigger Vercel deploy
              env:
                  VERCEL_DEPLOY_HOOK: ${{ secrets.VERCEL_DEPLOY_HOOK }}
              run: |
                  echo "Triggering Vercel deployment via Deploy Hook…"
                  curl -X POST "$VERCEL_DEPLOY_HOOK"
            - name: Log successful trigger
              run: echo "✅ Vercel deploy hook triggered successfully!"
